### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by BlueNightSky** [EKE00372/MooseLight#1]
7x MooseLight/MooseLight.lua:115: attempt to index global 'nameList' (a nil value)
[string "@MooseLight/MooseLight.lua"]:115: in function <MooseLight/MooseLight.lua:92>

Locals:
MapID = 2112
hour = 19
name = "翡翠區"
instanceID = 2444
(*temporary) = nil
(*temporary) = "巨龍群島"
(*temporary) = "none"
(*temporary) = "attempt to index global 'nameList' (a nil value)"
C_Map_GetBestMapForUnit = <function> defined =[C]:-1
GetGameTime = <function> defined =[C]:-1
GetSubZoneText = <function> defined =[C]:-1
GetInstanceInfo = <function> defined =[C]:-1
zoneLightID = <table> {
 1152 = true
 2095 = true
 1543 = true
 2133 = true
 2151 = true
 86 = true
 1169 = true
 1038 = true
 1162 = true
 885 = true
 1470 = true
 1571 = true
 1570 = true
 1469 = true
}
insLightID = <table> {
 533 = true
 1501 = true
 2162 = true
 2515 = true
 1711 = true
 1862 = true
 1176 = true
 2519 = true
 2284 = true
 329 = true
 1762 = true
 1466 = true
 1007 = true
 2520 = true
 289 = true
 1841 = true
}
SetCVar = <function> defined =[C]:-1
zoneDarkID = <table> {
 1533 = true
 1708 = true
 1707 = true
}
insDarkID = <table> {
 2285 = true
}
timeID = <table> {
 2024 = true
 896 = true
 2025 = true
 942 = true
 895 = true
 2023 = true
 2022 = true
}

**Comment by EKE00372** [comment]
#216e14d
